### ISSUE TITLE
yum "Error performing checksum" on CentOS 5

### ISSUE THREAD

**Issue by kovan** [dozzie/yumbootstrap#4]
Hi!. I am trying to install a CentOS 6 chroot on a CentOS 5 system, and I get:

http://mirror.centos.org/centos/6/os/x86_64/repodata/9a3a8909e656c27cd85c75a2d53b491040effa3f170b0369172433843e1829d7-primary.sqlite.bz2: [Errno -3] Error performing checksum
Trying other mirror.

Until I get:

Error: failure: repodata/9a3a8909e656c27cd85c75a2d53b491040effa3f170b0369172433843e1829d7-primary.sqlite.bz2 from centos: [Errno 256] No more mirrors to try.
"/usr/bin/yum" exited with code 1

Any ideas? thanks!

**Comment by dozzie** [comment]
Inability to install CentOS 6 under CentOS 5 is a known limitation (`KNOWN_ISSUES.md`; this was discovered under RHEL, but applies to CentOS as well). Unforunately, I don't have any good idea how to overcome this.

I'm affraid you will need a working CentOS 6 in order to build more CentOS 6 chroots. Maybe it could be worked around by upgrading Yum in a CentOS 5 chroot, but I haven't tried it. You may also try building Debian Wheezy chroot and running yumbootstrap from that one.

**Comment by kovan** [comment]
Ahh ok, thanks =)
